import React from 'react';
import './Dataview.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHome, faInfoCircle, faPhoneAlt, faTable, faQuestionCircle,faChartLine,faSearch } from '@fortawesome/free-solid-svg-icons';
import DataTable from './DataTable';
import logo from './image2.jpg'
const data = [
  {
    id: 1,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 2,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 3,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 4,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 5,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 6,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 7,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  {
    id: 8,
    Date: '2024-11-13',
    Time: '10:00',
    COMP_TYPE: 'Example',
    camA_OD: 'D',
    camB_OD: 'D',
    camC_OD: 'D',
    camD_OD: 'D',
    camA_OD_CL: 'D_CL',
    camB_OD_CL: 'D_CL',
    camC_OD_CL: 'D_CL',
    camD_OD_CL: 'D_CL',
    camA_SH: 'H',
    camB_SH_left: 'H_left',
    camB_SH_right: 'H_right',
    camC_SH: 'H',
    camD_SH_left: 'H_left',
    camD_SH_right: 'H_right',
    camA_WW: 'W',
    camB_WW_right: 'W_right',
    camB_WW_left: 'W_left',
    camC_WW: 'W',
    camD_WW_left: 'W_left',
    camD_WW_right: 'W_right',
    Reason: 'Example reason',
  },
  
  
  // Add more rows as needed
];

const DataView = ({ onSelect }) => {
  return (
    <div className="d-header">
      <img src={logo} alt="Display" className="logo" />
      <div className="d-menu-icons">
        <FontAwesomeIcon className="d-fa-icon" icon={faHome} onClick={() => onSelect('Home')} title="Home" />
        <FontAwesomeIcon className="d-fa-icon" icon={faChartLine} onClick={() => onSelect('Analysis')} title="Analysis" />
        <FontAwesomeIcon className="d-fa-icon" icon={faSearch} onClick={() => onSelect('Inspection')} title="Inspection" />
        {/* <FontAwesomeIcon icon={faPhoneAlt} onClick={() => onSelect('Contact Us')} title="Contactus" /> */}
        <FontAwesomeIcon className="d-fa-icon" icon={faInfoCircle} onClick={() => onSelect('About')} title="About" />
      </div>
      <div className="d-ground">
        {/* <h1>Dataview Page</h1> */}
        <DataTable data={data} />

      </div>
    </div>
  );
};

export default DataView;
